package com.app.shared

object AppConstants {
    object Broadcast {
        const val TOKEN_EXPIRED_VIA_API_ACTION = "TOKEN_EXPIRED_VIA_API_ACTION"
        const val APP_BACKGROUND_COLOR_ENABLE_CHANGED = "APP_BACKGROUND_COLOR_ENABLE_CHANGED"
        const val ACTIVITY_BACKGROUND_COLOR_ENABLE_CHANGED =
            "ACTIVITY_BACKGROUND_COLOR_ENABLE_CHANGED"
        const val APP_RESOURCES_CHANGED_ACTION = "APP_RESOURCES_CHANGED_ACTION"
    }

    object AppVersion {
        const val UPDATE_APP_VERSION_BROADCAST_ACTION = "UPDATE_APP_VERSION_BROADCAST_ACTION"
    }
}